# Use Node.js 20 image as base
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy Prisma schema directory
COPY prisma ./prisma/

# Copy application code
COPY . .

# Copy and allow running wait-for-it.sh script
COPY ci/wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

# Copy and allow running migrate-and-start.sh script
COPY ci/migrate-and-start.sh ./
RUN chmod +x migrate-and-start.sh

# Execute the script
CMD ["./migrate-and-start.sh"]